export type SearchResultsPageSuppressionRule = {
  hostSuffixes: string[];
  paths: string[];
  requiredQueryParams?: string[];
};

export type CompanyAliasSuffixStrippingConfig = {
  enabled: boolean;
  legalSuffixTokens: string[];
  genericTrailingTokens: string[];
};

export type AmazonPropertyMatchingConfig = {
  enabled: boolean;
  useBrand: boolean;
  useManufacturer: boolean;
  brandWeight: number;
  manufacturerWeight: number;
};

export type EbayJsonLdProductMatchingConfig = {
  enabled: boolean;
  useBrand: boolean;
  useManufacturer: boolean;
  brandWeight: number;
  manufacturerWeight: number;
};

export type MatchingConfig = {
  enableSubdomainMatching: boolean;
  enableMatchAcrossTLDs: boolean;
  enableEcommerceFamilyAliasMatching: boolean;
  restrictMetaPageContextToEcommerceHosts: boolean;
  urlSeedLimit: number;
  metaSeedLimit: number;
  urlMatchPriority: {
    exact: number;
    partial: number;
    subdomain: number;
  };
  pageContextWeights: {
    title: number;
    metaTitle: number;
    description: number;
    ogTitle: number;
    ogDescription: number;
  };
  pageContextTypeBoosts: {
    company: number;
    productLine: number;
    product: number;
  };
  pageContextMinEntityNameLength: number;
  marketplaceBrandDenylist: string[];
  amazonPropertyMatching: AmazonPropertyMatchingConfig;
  ebayJsonLdProductMatching: EbayJsonLdProductMatchingConfig;
  companyAliasSuffixStripping: CompanyAliasSuffixStrippingConfig;
  enableSearchResultsPageSuppressions: boolean;
  searchResultsPageSuppressions: SearchResultsPageSuppressionRule[];
  ecommerceDomainFamilyMap: Record<string, string>;
  ccTLDs: Set<string>;
  specificPathDomainMatches: string[];
};

const DEFAULT_MATCHING_CONFIG: MatchingConfig = {
  enableSubdomainMatching: true,
  enableMatchAcrossTLDs: true,
  enableEcommerceFamilyAliasMatching: true,
  restrictMetaPageContextToEcommerceHosts: true,
  urlSeedLimit: 3,
  metaSeedLimit: 5,
  urlMatchPriority: {
    exact: 3,
    partial: 2,
    subdomain: 1,
  },
  pageContextWeights: {
    title: 10,
    metaTitle: 9,
    description: 6,
    ogTitle: 9,
    ogDescription: 6,
  },
  pageContextTypeBoosts: {
    company: 3,
    productLine: 4,
    product: 4,
  },
  pageContextMinEntityNameLength: 3,
  marketplaceBrandDenylist: ["amazon", "ebay"],
  amazonPropertyMatching: {
    enabled: true,
    useBrand: true,
    useManufacturer: true,
    brandWeight: 16,
    manufacturerWeight: 12,
  },
  ebayJsonLdProductMatching: {
    enabled: true,
    useBrand: true,
    useManufacturer: true,
    brandWeight: 14,
    manufacturerWeight: 10,
  },
  companyAliasSuffixStripping: {
    enabled: true,
    legalSuffixTokens: [
      "inc",
      "incorporated",
      "corp",
      "corporation",
      "co",
      "company",
      "ltd",
      "limited",
      "llc",
      "plc",
      "lp",
      "llp",
      "gmbh",
      "ag",
      "sa",
      "nv",
      "bv",
      "oy",
      "oyj",
      "pte",
      "pty",
    ],
    genericTrailingTokens: [
      "group",
      "holdings",
      "industries",
      "industry",
      "systems",
      "technology",
      "technologies",
    ],
  },
  enableSearchResultsPageSuppressions: true,
  searchResultsPageSuppressions: [
    {
      hostSuffixes: ["google.com"],
      paths: ["/search"],
      requiredQueryParams: ["q"],
    },
    {
      hostSuffixes: ["bing.com"],
      paths: ["/search"],
      requiredQueryParams: ["q"],
    },
    {
      hostSuffixes: ["search.yahoo.com"],
      paths: ["/search"],
      requiredQueryParams: ["p"],
    },
    {
      hostSuffixes: ["duckduckgo.com"],
      paths: ["/"],
      requiredQueryParams: ["q"],
    },
  ],
  specificPathDomainMatches: ["github.com"],
  ecommerceDomainFamilyMap: {
    "amazon.com": "amazon",
    "amazon.ca": "amazon",
    "amazon.com.mx": "amazon",
    "amazon.com.br": "amazon",
    "amazon.co.uk": "amazon",
    "amazon.de": "amazon",
    "amazon.fr": "amazon",
    "amazon.it": "amazon",
    "amazon.es": "amazon",
    "amazon.nl": "amazon",
    "amazon.se": "amazon",
    "amazon.pl": "amazon",
    "amazon.com.be": "amazon",
    "amazon.com.tr": "amazon",
    "amazon.eg": "amazon",
    "amazon.sa": "amazon",
    "amazon.ae": "amazon",
    "amazon.in": "amazon",
    "amazon.sg": "amazon",
    "amazon.com.au": "amazon",
    "amazon.co.jp": "amazon",
    "ebay.com": "ebay",
    "ebay.ca": "ebay",
    "ebay.com.mx": "ebay",
    "ebay.com.br": "ebay",
    "ebay.co.uk": "ebay",
    "ebay.de": "ebay",
    "ebay.fr": "ebay",
    "ebay.it": "ebay",
    "ebay.es": "ebay",
    "ebay.nl": "ebay",
    "ebay.be": "ebay",
    "ebay.pl": "ebay",
    "ebay.ie": "ebay",
    "ebay.at": "ebay",
    "ebay.ch": "ebay",
    "ebay.com.au": "ebay",
    "ebay.com.hk": "ebay",
    "ebay.ph": "ebay",
    "ebay.my": "ebay",
    "ebay.sg": "ebay",
  },
  ccTLDs: new Set([
    "ac",
    "ad",
    "ae",
    "af",
    "ag",
    "ai",
    "al",
    "am",
    "an",
    "ao",
    "aq",
    "ar",
    "as",
    "at",
    "au",
    "aw",
    "ax",
    "az",
    "ba",
    "bb",
    "bd",
    "be",
    "bf",
    "bg",
    "bh",
    "bi",
    "bj",
    "bl",
    "bm",
    "bn",
    "bo",
    "bq",
    "br",
    "bs",
    "bt",
    "bv",
    "bw",
    "by",
    "bz",
    "ca",
    "cc",
    "cd",
    "cf",
    "cg",
    "ch",
    "ci",
    "ck",
    "cl",
    "cm",
    "cn",
    "co",
    "cr",
    "cu",
    "cv",
    "cw",
    "cx",
    "cy",
    "cz",
    "de",
    "dj",
    "dk",
    "dm",
    "do",
    "dz",
    "ec",
    "ee",
    "eg",
    "eh",
    "er",
    "es",
    "et",
    "eu",
    "fi",
    "fj",
    "fk",
    "fm",
    "fo",
    "fr",
    "ga",
    "gb",
    "gd",
    "ge",
    "gf",
    "gg",
    "gh",
    "gi",
    "gl",
    "gm",
    "gn",
    "gp",
    "gq",
    "gr",
    "gs",
    "gt",
    "gu",
    "gw",
    "gy",
    "hk",
    "hm",
    "hn",
    "hr",
    "ht",
    "hu",
    "id",
    "ie",
    "il",
    "im",
    "in",
    "io",
    "iq",
    "ir",
    "is",
    "it",
    "je",
    "jm",
    "jo",
    "jp",
    "ke",
    "kg",
    "kh",
    "ki",
    "km",
    "kn",
    "kp",
    "kr",
    "kw",
    "ky",
    "kz",
    "la",
    "lb",
    "lc",
    "li",
    "lk",
    "lr",
    "ls",
    "lt",
    "lu",
    "lv",
    "ly",
    "ma",
    "mc",
    "md",
    "me",
    "mf",
    "mg",
    "mh",
    "mk",
    "ml",
    "mm",
    "mn",
    "mo",
    "mp",
    "mq",
    "mr",
    "ms",
    "mt",
    "mu",
    "mv",
    "mw",
    "mx",
    "my",
    "mz",
    "na",
    "nc",
    "ne",
    "nf",
    "ng",
    "ni",
    "nl",
    "no",
    "np",
    "nr",
    "nu",
    "nz",
    "om",
    "pa",
    "pe",
    "pf",
    "pg",
    "ph",
    "pk",
    "pl",
    "pm",
    "pn",
    "pr",
    "ps",
    "pt",
    "pw",
    "py",
    "qa",
    "re",
    "ro",
    "rs",
    "ru",
    "rw",
    "sa",
    "sb",
    "sc",
    "sd",
    "se",
    "sg",
    "sh",
    "si",
    "sj",
    "sk",
    "sl",
    "sm",
    "sn",
    "so",
    "sr",
    "ss",
    "st",
    "su",
    "sv",
    "sx",
    "sy",
    "sz",
    "tc",
    "td",
    "tf",
    "tg",
    "th",
    "tj",
    "tk",
    "tl",
    "tm",
    "tn",
    "to",
    "tp",
    "tr",
    "tt",
    "tv",
    "tw",
    "tz",
    "ua",
    "ug",
    "uk",
    "um",
    "us",
    "uy",
    "uz",
    "va",
    "vc",
    "ve",
    "vg",
    "vi",
    "vn",
    "vu",
    "wf",
    "ws",
    "xn--2scrj9c",
    "xn--3e0b707e",
    "xn--3hcrj9c",
    "xn--4dbrk0ce",
    "xn--45br5cyl",
    "xn--45brj9c",
    "xn--4dbrk0ce",
    "xn--54b7fta0cc",
    "xn--80ao21a",
    "xn--90a3ac",
    "xn--90ae",
    "xn--90ais",
    "xn--clchc0ea0b2g2a9gcd",
    "xn--d1alf",
    "xn--e1a4c",
    "xn--fiqs8s",
    "xn--fiqz9s",
    "xn--fpcrj9c3d",
    "xn--fzc2c9e2c",
    "xn--gecrj9c",
    "xn--h2breg3eve",
    "xn--h2brj9c",
    "xn--h2brj9c8c",
    "xn--j1amh",
    "xn--j6w193g",
    "xn--kprw13d",
    "xn--kpry57d",
    "xn--l1acc",
    "xn--lgbbat1ad8j",
    "xn--mgb2ddes",
    "xn--mgb9awbf",
    "xn--mgba3a4f16a",
    "xn--mgbaam7a8h",
    "xn--mgbah1a3hjkrd",
    "xn--mgbai9azgqp6j",
    "xn--mgbayh7gpa",
    "xn--mgbbh1a",
    "xn--mgbbh1a71e",
    "xn--mgbc0a9azcg",
    "xn--mgbcpq6gpa1a",
    "xn--mgberp4a5d4ar",
    "xn--mgbgu82a",
    "xn--mgbpl2fh",
    "xn--mgbtx2b",
    "xn--mgbx4cd0ab",
    "xn--mix082f",
    "xn--mix891f",
    "xn--node",
    "xn--o3cw4h",
    "xn--ogbpf8fl",
    "xn--p1ai",
    "xn--pgbs0dh",
    "xn--q7ce6a",
    "xn--qxa6a",
    "xn--qxam",
    "xn--rvc1e0am3e",
    "xn--s9brj9c",
    "xn--wgbh1c",
    "xn--wgbl6a",
    "xn--xkc2al3hye2a",
    "xn--xkc2dl3a5ee0h",
    "xn--y9a3aq",
    "xn--yfro4i67o",
    "xn--ygbi2ammx",
    "ye",
    "yt",
    "za",
    "zm",
    "zw",
  ]),
};

export const matchingConfig: MatchingConfig = {
  ...DEFAULT_MATCHING_CONFIG,
};

export const setMatchingConfig = (overrides: Partial<MatchingConfig>): void => {
  Object.assign(matchingConfig, overrides);
};

export const resetMatchingConfig = (): void => {
  Object.assign(matchingConfig, DEFAULT_MATCHING_CONFIG);
};
