import fs from "node:fs/promises";
import path from "node:path";
import countries from "i18n-iso-countries";

const COUNTRY_CODES_OUTPUT_PATH = path.resolve(
  import.meta.dirname,
  "../src/generated/matching/generatedCountryCodeSuffixes.ts",
);
const COMPOUND_PREFIXES_OUTPUT_PATH = path.resolve(
  import.meta.dirname,
  "../src/generated/matching/generatedCompoundSuffixPrefixes.ts",
);
const COMPOUND_PREFIX_POLICY_PATH = path.resolve(
  import.meta.dirname,
  "../src/lib/matching/compoundSuffixPrefixPolicy.json",
);
const PSL_URL = "https://publicsuffix.org/list/public_suffix_list.dat";

const EXTRA_CC_TLD_SUFFIXES = ["eu", "uk"];
const EXCLUDED_SUFFIXES = new Set(["xk"]);

const buildCountryCodeSuffixes = (): string[] => {
  const alpha2Codes = Object.keys(countries.getAlpha2Codes());
  return Array.from(
    new Set(
      [...alpha2Codes.map((code) => code.toLowerCase()), ...EXTRA_CC_TLD_SUFFIXES]
        .filter((code) => /^[a-z]{2}$/.test(code))
        .filter((code) => !EXCLUDED_SUFFIXES.has(code)),
    ),
  ).sort((left, right) => left.localeCompare(right));
};

const buildCountryCodeFile = (suffixes: string[]): string => {
  return `// Generated by scripts/update-country-code-suffixes.ts\n// Source: i18n-iso-countries alpha-2 codes, plus explicit ccTLD exceptions.\nexport const GENERATED_COUNTRY_CODE_SUFFIXES = ${JSON.stringify(
    suffixes,
    null,
    2,
  )} as const;\n`;
};

const buildCompoundPrefixFile = (prefixes: string[]): string => {
  return `// Generated by scripts/update-country-code-suffixes.ts\n// Source: publicsuffix.org list, filtered through local generic-prefix policy.\nexport const GENERATED_COMPOUND_SUFFIX_PREFIXES = ${JSON.stringify(
    prefixes,
    null,
    2,
  )} as const;\n`;
};

const writeFileIfChanged = async (
  outputPath: string,
  nextContents: string,
): Promise<boolean> => {
  const currentContents = await fs
    .readFile(outputPath, "utf8")
    .catch(() => null as string | null);

  if (currentContents === nextContents) return false;

  await fs.mkdir(path.dirname(outputPath), { recursive: true });
  await fs.writeFile(outputPath, nextContents, "utf8");
  return true;
};

const normalizePslRule = (rule: string): string => {
  return rule.replace(/^!/, "").replace(/^\*\./, "");
};

const fetchPslRules = async (): Promise<string[]> => {
  const response = await fetch(PSL_URL, { cache: "no-store" });
  if (!response.ok) {
    throw new Error(`Failed to fetch public suffix list (${response.status})`);
  }

  const text = await response.text();
  return text
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter((line) => line.length > 0 && !line.startsWith("//"))
    .map(normalizePslRule)
    .filter((line) => /^[a-z0-9.-]+$/i.test(line));
};

const readCompoundPrefixPolicy = async (): Promise<string[]> => {
  const raw = await fs.readFile(COMPOUND_PREFIX_POLICY_PATH, "utf8");
  const parsed = JSON.parse(raw) as unknown;

  if (!Array.isArray(parsed)) {
    throw new Error("compound suffix prefix policy must be a JSON array");
  }

  return parsed
    .filter((value): value is string => typeof value === "string")
    .map((value) => value.toLowerCase())
    .filter((value) => /^[a-z0-9-]+$/.test(value));
};

const buildCompoundSuffixPrefixes = async (
  countryCodeSuffixes: string[],
): Promise<string[]> => {
  const countrySuffixSet = new Set(countryCodeSuffixes);
  const observedPrefixes = new Set<string>();
  const allowedPrefixes = await readCompoundPrefixPolicy();

  for (const rule of await fetchPslRules()) {
    const parts = rule
      .toLowerCase()
      .split(".")
      .filter(Boolean);
    if (parts.length !== 2) continue;

    const [prefix, countryCode] = parts;
    if (!countrySuffixSet.has(countryCode)) continue;
    observedPrefixes.add(prefix);
  }

  return allowedPrefixes.filter((prefix) =>
    observedPrefixes.has(prefix),
  );
};

const main = async (): Promise<void> => {
  const suffixes = buildCountryCodeSuffixes();
  const compoundPrefixes = await buildCompoundSuffixPrefixes(suffixes);
  const countryCodeFile = buildCountryCodeFile(suffixes);
  const compoundPrefixFile = buildCompoundPrefixFile(compoundPrefixes);

  const countryCodeChanged = await writeFileIfChanged(
    COUNTRY_CODES_OUTPUT_PATH,
    countryCodeFile,
  );
  const compoundPrefixesChanged = await writeFileIfChanged(
    COMPOUND_PREFIXES_OUTPUT_PATH,
    compoundPrefixFile,
  );
  console.log(
    `${countryCodeChanged ? "Wrote" : "Kept"} ${suffixes.length} country-code suffixes in ${path.relative(process.cwd(), COUNTRY_CODES_OUTPUT_PATH)}`,
  );
  console.log(
    `${compoundPrefixesChanged ? "Wrote" : "Kept"} ${compoundPrefixes.length} compound suffix prefixes in ${path.relative(process.cwd(), COMPOUND_PREFIXES_OUTPUT_PATH)}`,
  );
};

void main();
